# Generated by Django 4.0.2 on 2022-03-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='Your username', max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Avatar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=50)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchamp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='')),
                ('Class', models.CharField(choices=[('Innovator', 'Innovator'), ('Assassin', 'Assassin'), ('Scholar', 'Scholar'), ('Sniper', 'Sniper'), ('Striker', 'Striker'), ('Transformer', 'Transformer'), ('Bruiser', 'Bruiser'), ('Challenger', 'Challenger'), ('Colossus', 'Colossus'), ('Enchanter', 'Enchanter'), ('Twinshot', 'Twinshot'), ('Arcanist', 'Arcanist'), ('Bodyguard', 'Bodyguard')], max_length=100)),
                ('Origin', models.CharField(choices=[('Enforcer', 'Enforcer'), ('Glutton', 'Glutton'), ('Mastermind', 'Mastermind'), ('Rival', 'Rival'), ('Socialite', 'Socialite'), ('Yordle-Lord', 'Yordle-Lord'), ('Debonair', 'Debonair'), ('Scrap', 'Scrap'), ('Chemtech', 'Chemtech'), ('Clockwork', 'Clockwork'), ('Mutant', 'Mutant'), ('Syndicate', 'Syndicate'), ('Hextech', 'Hextech'), ('Mercenary', 'Mercenary'), ('Yordle', 'Yordle')], max_length=100)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchamp.teambuilder')),
            ],
        ),
    ]
