# Generated by Django 4.0.2 on 2022-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='Team',
        ),
        migrations.AddField(
            model_name='champion',
            name='Money',
            field=models.IntegerField(default=0),
        ),
    ]
