# Generated by Django 4.0.2 on 2022-03-26 15:01

import _queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchamp', '0002_remove_champion_team_champion_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='Special',
            field=models.CharField(default=_queue.Empty, max_length=100),
        ),
    ]
