# Generated by Django 4.0.2 on 2022-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchamp', '0006_remove_champion_team_champion_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
