# Generated by Django 4.0.2 on 2022-05-02 19:08

import _queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchamp', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='MadeFrom1',
            field=models.CharField(choices=[('B.F. Sword', 'B.F. Sword'), ('Chain Vest', 'Chain Vest'), ('Giants Belt', 'Giants Belt'), ('Needlessly Large Rod', 'Needlessly Large Rod'), ('Negatron Cloak', 'Negatron Cloak'), ('Recurve Bow', 'Recurve Bow'), ('Sparring Gloves', 'Sparring Gloves'), ('Spatula', 'Spatula'), ('Tear of the Goddess', 'Tear of the Goddess')], default=_queue.Empty, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='MadeFrom2',
            field=models.CharField(choices=[('B.F. Sword', 'B.F. Sword'), ('Chain Vest', 'Chain Vest'), ('Giants Belt', 'Giants Belt'), ('Needlessly Large Rod', 'Needlessly Large Rod'), ('Negatron Cloak', 'Negatron Cloak'), ('Recurve Bow', 'Recurve Bow'), ('Sparring Gloves', 'Sparring Gloves'), ('Spatula', 'Spatula'), ('Tear of the Goddess', 'Tear of the Goddess')], default=_queue.Empty, max_length=100),
        ),
    ]
