# Generated by Django 4.0.2 on 2022-05-03 09:20

import _queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchamp', '0009_alter_item_madefrom1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='MadeFrom2',
            field=models.CharField(choices=[('B.F.Sword', 'B.F.Sword'), ('ChainVest', 'ChainVest'), ('GiantsBelt', 'GiantsBelt'), ('NeedlesslyLargeRod', 'NeedlesslyLargeRod'), ('NegatronCloak', 'NegatronCloak'), ('RecurveBow', 'RecurveBow'), ('SparringGloves', 'SparringGloves'), ('Spatula', 'Spatula'), ('TearoftheGoddess', 'TearoftheGoddess')], default=_queue.Empty, max_length=100),
        ),
    ]
